# Generated by Django 5.1.4 on 2024-12-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_inventory_alter_reserva_number_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
